(()=>{
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],R=(a,b)=>Math.floor(Math.random()*(b-a+1))+a,C=p=>Math.random()<p,SAVE='abyssCellsMobile_v1';
const roomMeta={start:['🔥','safe'],enemy:['👹','enemy'],elite:['💀','enemy'],gold:['🪙','loot'],chest:['🧰','loot'],item:['⚔️','loot'],shop:['🏪','safe'],heal:['⛲','safe'],event:['🗿','magic'],trap:['🕸️','enemy'],stairs:['🚪','magic'],boss:['🐲','enemy']};
const enemies=[['Пещерный слизень','🟢',16,5],['Костяной вор','💀',20,6],['Голодный волк','🐺',23,7],['Культист','🧙',27,8],['Каменный страж','🗿',32,9],['Теневой рыцарь','🥷',36,10]];
const bosses=[['Пожиратель комнат','🐲',75,13],['Королева нитей','🕷️',92,15],['Безликий надзиратель','👁️',110,17],['Костяной монарх','👑',132,20]];
const itemNames={weapon:['Ржавый клинок','Клык бездны','Молот палача','Коса ночи'],armor:['Кожаный панцирь','Кольчуга стража','Броня титана','Плащ теней'],ring:['Медное кольцо','Перстень охотника','Кольцо крови','Печать судьбы'],amulet:['Амулет искры','Глаз путника','Сердце глубин','Звезда бездны'],boots:['Сапоги бродяги','Шаги ветра','Когти охотника','Тихие подошвы'],helm:['Старый капюшон','Шлем дозорного','Рогатая маска','Корона пепла']};
const slots=['weapon','helm','armor','ring','boots','amulet'],slotIcon={weapon:'⚔️',helm:'⛑️',armor:'🛡️',ring:'💍',boots:'🥾',amulet:'📿'};
let state,combat=null,guard=false;
function fresh(){return{floor:1,current:12,revealed:1,cells:[],hero:{level:1,xp:0,next:55,hp:42,max:42,energy:3,maxEnergy:3,gold:0,potions:2,keys:0,atk:8,def:2,crit:8,luck:0,equip:{}},stats:{kills:0,bosses:0,opened:1},log:[]}}
function neighbors(i){const x=i%5,y=Math.floor(i/5),a=[];if(x>0)a.push(i-1);if(x<4)a.push(i+1);if(y>0)a.push(i-5);if(y<4)a.push(i+5);return a}
function weighted(){const f=state.floor,r=Math.random();if(r<.29)return'enemy';if(r<.36)return'gold';if(r<.45)return'chest';if(r<.53)return'item';if(r<.60)return'event';if(r<.67)return'trap';if(r<.73)return'heal';if(r<.79)return'shop';if(r<.88)return'enemy';return f>2&&C(.24)?'elite':'enemy'}
function initFloor(){state.current=12;state.revealed=1;state.cells=Array.from({length:25},(_,i)=>({i,type:null,revealed:false,used:false}));Object.assign(state.cells[12],{type:'start',revealed:true,used:true});let exit;do exit=R(0,24);while(exit===12||Math.abs(exit%5-2)+Math.abs(Math.floor(exit/5)-2)<3);state.cells[exit].type=state.floor%5===0?'boss':'stairs';log(`Ты входишь на этаж ${state.floor}.`);render();save()}
function reachable(i){if(combat)return false;const c=state.cells[i];return !c.revealed&&neighbors(state.current).includes(i)}
function moveTo(i){const c=state.cells[i];if(!reachable(i)&&!(c.revealed&&neighbors(state.current).includes(i)))return;state.current=i;if(!c.revealed){c.revealed=true;c.type=c.type||weighted();state.revealed++;state.stats.opened++;resolve(c)}else render();save()}
function resolve(c){c.used=true;const t=c.type;if(t==='start')render();else if(t==='gold'){const n=R(10,26)+state.floor*2;gainGold(n);notify('Золото',`Ты нашёл ${n} монет.`);log(`Найдено ${n} золота.`);render()}else if(t==='chest')chest(c);else if(t==='item')offerItem(makeItem());else if(t==='enemy'||t==='elite'||t==='boss')startCombat(t);else if(t==='heal')healRoom();else if(t==='shop')shop();else if(t==='event')randomEvent();else if(t==='trap')trap();else if(t==='stairs')stairs();}
function chest(c){if(state.hero.keys>0){showEvent('Запертый сундук','🧰','В замке поворачивается ключ.',[{t:'Открыть ключом',s:'Редкая добыча',f:()=>{state.hero.keys--;closeEvent();offerItem(makeItem(2))}},{t:'Оставить',s:'Сохранить ключ',f:closeEvent}])}else{const n=R(15,35);gainGold(n);if(C(.35))state.hero.keys++;notify('Сундук открыт',`Внутри ${n} золота${state.hero.keys?' и ключ':''}.`);log('Ты обыскал старый сундук.');render()}}
function stairs(){showEvent('Спуск глубже','🚪','За дверью слышится гул следующего этажа.',[{t:'Спуститься',s:'Начать новый этаж',f:()=>{closeEvent();state.floor++;state.hero.energy=state.hero.maxEnergy;initFloor()}},{t:'Остаться',s:'Исследовать текущий этаж',f:closeEvent}])}
function healRoom(){const n=Math.max(10,Math.round(state.hero.max*.32));showEvent('Источник жизни','⛲','Холодная вода восстанавливает силы.',[{t:'Выпить',s:`Восстановить ${n} HP`,f:()=>{heal(n);closeEvent();render()}},{t:'Набрать эликсир',s:'+1 эликсир',f:()=>{state.hero.potions++;closeEvent();render()}}])}
function trap(){const d=Math.max(3,R(5,11)-Math.floor(totalDef()/2));state.hero.hp-=d;log(`Ловушка наносит ${d} урона.`);notify('Ловушка',`-${d} HP`);if(state.hero.hp<=0)die('древняя ловушка');else render()}
function randomEvent(){const e=R(1,4);if(e===1)showEvent('Кровавый алтарь','🩸','Камень предлагает силу в обмен на кровь.',[{t:'Принять сделку',s:'-9 HP, +2 атаки',f:()=>{state.hero.hp=Math.max(1,state.hero.hp-9);state.hero.atk+=2;closeEvent();log('Алтарь усилил твой клинок.');render()}},{t:'Уйти',s:'Без риска',f:closeEvent}]);if(e===2)showEvent('Потерянный путник','🧑‍🦯','Он предлагает обменять карту на немного золота.',[{t:'Заплатить 18',s:'Открыть две соседние ячейки',f:()=>{if(state.hero.gold<18)return notify('Не хватает золота','Нужно 18 монет.');state.hero.gold-=18;neighbors(state.current).filter(i=>!state.cells[i].revealed).slice(0,2).forEach(i=>{state.cells[i].revealed=true;state.cells[i].type=state.cells[i].type||weighted();state.revealed++});closeEvent();render()}},{t:'Отказаться',s:'Продолжить путь',f:closeEvent}]);if(e===3)showEvent('Кости судьбы','🎲','Бросок может принести богатство или боль.',[{t:'Бросить',s:'50 на 50',f:()=>{closeEvent();if(C(.5)){gainGold(45);notify('Удача','+45 золота')}else{state.hero.hp-=12;notify('Неудача','-12 HP');if(state.hero.hp<=0)die('кости судьбы')}render()}},{t:'Не рисковать',s:'Уйти',f:closeEvent}]);if(e===4)showEvent('Память бездны','🔮','В кристалле застыло чужое мастерство.',[{t:'Поглотить',s:'+25 опыта',f:()=>{gainXp(25);closeEvent();render()}},{t:'Разбить',s:'Шанс получить предмет',f:()=>{closeEvent();C(.55)?offerItem(makeItem(1)):notify('Пусто','Кристалл рассыпался в пыль.')}}])}
function shop(){const a=makeItem(),b=makeItem(1);showEvent('Торговец глубин','🏪','У него есть всё необходимое для следующего боя.',[{t:`${a.icon} ${a.name} — 42`,s:a.desc,f:()=>buyItem(a,42)},{t:`${b.icon} ${b.name} — 68`,s:b.desc,f:()=>buyItem(b,68)},{t:'🧪 Эликсир — 24',s:'Восстановление в бою',f:()=>{if(pay(24)){state.hero.potions++;notify('Куплено','+1 эликсир');render()}}},{t:'Уйти',s:'Ничего не покупать',f:closeEvent}])}
function pay(n){if(state.hero.gold<n){notify('Не хватает золота',`Нужно ${n}.`);return false}state.hero.gold-=n;return true}
function buyItem(it,n){if(!pay(n))return;equip(it);closeEvent();notify('Куплено',it.name)}
function makeItem(bonus=0){const slot=slots[R(0,slots.length-1)],tier=Math.min(3,Math.max(0,Math.floor((state.floor+bonus+R(0,4))/4))),name=itemNames[slot][tier],power=2+tier*2+Math.floor(state.floor/4);let stat,desc;if(slot==='weapon'){stat={atk:power+2};desc=`+${stat.atk} к атаке`}else if(slot==='armor'||slot==='helm'){stat={def:Math.max(1,Math.ceil(power/2)),hp:power*2};desc=`+${stat.def} защита, +${stat.hp} HP`}else if(slot==='ring'){stat={crit:3+tier*2};desc=`+${stat.crit}% крит`}else if(slot==='boots'){stat={def:1+tier,luck:1+tier};desc=`+${stat.def} защита, +${stat.luck} удача`}else{stat={atk:1+tier,hp:4+power};desc=`+${stat.atk} атака, +${stat.hp} HP`}return{slot,name,icon:slotIcon[slot],tier,stat,desc}}
function offerItem(it){showEvent('Найден предмет',it.icon,`${it.name}. ${it.desc}.`,[{t:'Экипировать',s:'Заменить предмет в этом слоте',f:()=>{equip(it);closeEvent();notify('Экипировано',it.name)}},{t:'Продать',s:`Получить ${18+it.tier*10} золота`,f:()=>{gainGold(18+it.tier*10);closeEvent();render()}}])}
function equip(it){state.hero.equip[it.slot]=it;state.hero.hp=Math.min(state.hero.hp,totalMax());render();save()}
function stat(k){return Object.values(state.hero.equip).reduce((n,i)=>n+(i.stat[k]||0),0)}
function totalAtk(){return state.hero.atk+stat('atk')}function totalDef(){return state.hero.def+stat('def')}function totalCrit(){return state.hero.crit+stat('crit')}function totalMax(){return state.hero.max+stat('hp')}
function startCombat(type){const boss=type==='boss',elite=type==='elite';let base=boss?bosses[(Math.floor(state.floor/5)-1)%bosses.length]:enemies[Math.min(enemies.length-1,Math.floor((state.floor-1)/2)+R(0,1))];const scale=1+(state.floor-1)*.14+(elite?.35:0);combat={name:(elite?'Элита: ':'')+base[0],icon:base[1],hp:Math.round(base[2]*scale),max:Math.round(base[2]*scale),atk:Math.round(base[3]*scale),boss,elite,turn:0};guard=false;$('#combat').classList.add('show');combatMsg(`${combat.name} преграждает путь.`);renderCombat();save()}
function playerAttack(skill=false){if(!combat)return;if(skill&&state.hero.energy<2)return notify('Недостаточно энергии','Нужно 2 энергии.');if(skill)state.hero.energy-=2;let dmg=Math.max(1,totalAtk()+R(-2,3));if(skill)dmg=Math.round(dmg*1.75);const crit=C(totalCrit()/100);if(crit)dmg=Math.round(dmg*1.7);combat.hp-=dmg;combatMsg(`${skill?'Сильный удар':'Атака'} наносит ${dmg}${crit?' критического':''} урона.`);if(combat.hp<=0)return winCombat();enemyTurn()}
function enemyTurn(){if(!combat)return;combat.turn++;let dmg=Math.max(1,combat.atk+R(-2,2)-totalDef());if(guard){dmg=Math.max(0,Math.round(dmg*.3));guard=false}if(combat.boss&&combat.turn%3===0)dmg+=4+Math.floor(state.floor/2);state.hero.hp-=dmg;combatMsg(`${combat.name} наносит ${dmg} урона.`);if(state.hero.hp<=0){$('#combat').classList.remove('show');die(combat.name);return}state.hero.energy=Math.min(state.hero.maxEnergy,state.hero.energy+1);render();renderCombat();save()}
function winCombat(){const c=combat;combat=null;$('#combat').classList.remove('show');state.stats.kills++;if(c.boss)state.stats.bosses++;const g=R(c.boss?55:c.elite?24:10,c.boss?90:c.elite?45:24)+state.floor*2,x=c.boss?60:c.elite?34:18;gainGold(g);gainXp(x);state.hero.energy=Math.min(state.hero.maxEnergy,state.hero.energy+1);log(`Победа: ${c.name}. +${g} золота, +${x} опыта.`);notify(c.boss?'Босс повержен':'Победа',`+${g} золота · +${x} опыта`);if(c.boss)setTimeout(()=>showEvent('Сердце этажа','🏆','За поверженным боссом открывается проход.',[{t:'Спуститься',s:'Следующий этаж',f:()=>{closeEvent();state.floor++;initFloor()}}]),180);render();save()}
function usePotion(){if(!combat||state.hero.potions<1)return notify('Нет эликсиров','Найди или купи эликсир.');state.hero.potions--;const n=Math.round(totalMax()*.42);heal(n);combatMsg(`Эликсир восстанавливает ${n} HP.`);enemyTurn()}
function gainGold(n){state.hero.gold+=n}function heal(n){state.hero.hp=Math.min(totalMax(),state.hero.hp+n)}
function gainXp(n){state.hero.xp+=n;while(state.hero.xp>=state.hero.next){state.hero.xp-=state.hero.next;state.hero.level++;state.hero.next=Math.round(state.hero.next*1.28);state.hero.max+=7;state.hero.atk+=2;if(state.hero.level%2===0)state.hero.def++;state.hero.hp=totalMax();state.hero.potions++;notify('Новый уровень',`Уровень ${state.hero.level}: характеристики выросли.`);log(`Достигнут уровень ${state.hero.level}.`)}}
function die(by){localStorage.removeItem(SAVE);showEvent('Экспедиция окончена','☠️',`Тебя остановил ${by}. Достигнут этаж ${state.floor}, побеждено врагов: ${state.stats.kills}.`,[{t:'Начать заново',s:'Новая случайная экспедиция',f:()=>{closeEvent();newGame()}}])}
function showEvent(title,icon,text,choices){$('#eventModal').innerHTML=`<div class="sub">СОБЫТИЕ</div><h2>${title}</h2><div class="art">${icon}</div><p class="mut">${text}</p><div class="choices">${choices.map((c,i)=>`<button class="choice" data-i="${i}"><b>${c.t}</b><small>${c.s||''}</small></button>`).join('')}</div>`;$('#event').classList.add('show');$$('.choice').forEach(b=>b.onclick=()=>choices[+b.dataset.i].f())}
function closeEvent(){$('#event').classList.remove('show');save()}
function combatMsg(x){if(!combat)return;combat.lines=combat.lines||[];combat.lines.push(x);if(combat.lines.length>8)combat.lines.shift();$('#combatLog').innerHTML=combat.lines.map(v=>`<div>${v}</div>`).join('');$('#combatLog').scrollTop=999}
function renderCombat(){if(!combat)return;$('#enemyIcon').textContent=combat.icon;$('#enemyName').textContent=combat.name;$('#eCombat').textContent=`HP ${Math.max(0,combat.hp)} / ${combat.max} · ATK ${combat.atk}`;$('#pCombat').textContent=`HP ${Math.max(0,state.hero.hp)} / ${totalMax()} · ATK ${totalAtk()}`;$('#skillBtn').disabled=state.hero.energy<2;$('#potionBtn').textContent=`🧪 Эликсир (${state.hero.potions})`}
function roman(n){const r=['','I','II','III','IV','V','VI','VII','VIII','IX','X'];return n<11?r[n]:n}
function buildName(){if(totalCrit()>=20)return'Критический дуэлянт';if(totalDef()>=11)return'Железный странник';if(totalAtk()>=24)return'Клинок бездны';if(state.hero.level>=8)return'Ветеран глубин';return'Безымянная сборка'}
function render(){const h=state.hero,m=totalMax();h.hp=Math.min(h.hp,m);$('#lvl').textContent=h.level;$('#atk').textContent=totalAtk();$('#def').textContent=totalDef();$('#crit').textContent=totalCrit()+'%';$('#gold').textContent=h.gold;$('#potions').textContent=h.potions;$('#keys').textContent=h.keys;$('#build').textContent=buildName();$('#hpText').textContent=`${Math.max(0,h.hp)} / ${m}`;$('#xpText').textContent=`${h.xp} / ${h.next}`;$('#enText').textContent=`${h.energy} / ${h.maxEnergy}`;$('#hpBar').style.width=100*h.hp/m+'%';$('#xpBar').style.width=100*h.xp/h.next+'%';$('#enBar').style.width=100*h.energy/h.maxEnergy+'%';$('#floorTitle').textContent=`Этаж ${roman(state.floor)}`;$('#depth').textContent=`Глубина ${state.floor}`;$('#opened').textContent=`Открыто ${state.revealed} / 25`;$('#grid').innerHTML=state.cells.map(c=>{const meta=roomMeta[c.type||'start'];return`<button class="cell ${c.revealed?'':'hidden'} ${reachable(c.i)?'reach':''} ${c.i===state.current?'now':''} ${c.used?'used':''} ${c.revealed?meta[1]:''}" data-i="${c.i}">${c.revealed?meta[0]:'◆'}</button>`}).join('');$$('.cell').forEach(b=>b.onclick=()=>moveTo(+b.dataset.i));$('#equip').innerHTML=slots.map(s=>{const i=h.equip[s];return`<div class="slot ${i?'has':''}" title="${i?i.desc:s}">${i?`<div><span>${i.icon}</span>${i.name.split(' ')[0]}</div>`:`<div><span>${slotIcon[s]}</span>пусто</div>`}</div>`}).join('');$('#log').innerHTML=state.log.slice(-15).reverse().map(x=>`<div>${x}</div>`).join('');if(combat)renderCombat()}
function log(x){state.log.push(x);if(state.log.length>60)state.log.shift()}
function notify(a,b){const t=$('#toast');t.innerHTML=`<b>${a}</b><div class="sub">${b}</div>`;t.classList.add('show');clearTimeout(t.timer);t.timer=setTimeout(()=>t.classList.remove('show'),2300)}
function save(){try{localStorage.setItem(SAVE,JSON.stringify({state,combat,guard}))}catch(e){}}
function load(){try{const x=JSON.parse(localStorage.getItem(SAVE));if(!x)return false;state=x.state;combat=x.combat;guard=x.guard;$('#start').classList.add('hide');render();if(combat){$('#combat').classList.add('show');renderCombat()}return true}catch(e){return false}}
function newGame(){state=fresh();combat=null;guard=false;$('#event').classList.remove('show');$('#combat').classList.remove('show');$('#start').classList.add('hide');initFloor()}
$('#newBtn').onclick=newGame;$('#continueBtn').disabled=!localStorage.getItem(SAVE);$('#continueBtn').onclick=()=>load()||newGame();$('#saveBtn').onclick=()=>{save();notify('Сохранено','Прогресс хранится в Safari.')};$('#resetBtn').onclick=()=>{if(confirm('Начать новую экспедицию?'))newGame()};$('#attackBtn').onclick=()=>playerAttack(false);$('#skillBtn').onclick=()=>playerAttack(true);$('#guardBtn').onclick=()=>{if(!combat)return;guard=true;combatMsg('Ты принимаешь защитную стойку.');enemyTurn()};$('#potionBtn').onclick=usePotion;window.addEventListener('beforeunload',save);
})();
